### PR TITLE
fix kafka user config with null values only

### LINKED ISSUE #1033: creating a new kafka cluster with v3.11.0 fails
Hi @ivan-savciuc @Serpentiel ,

I am trying to create a kafka cluster with `v3.11.0` and it fails with the following error:
```bash
aiven_kafka.aiven_kafka: Creating...
╷
│ Error: error converting user config options for service type kafka to API format: kafka_user_config.0.kafka: not a map
│
│   with aiven_kafka.aiven_kafka,
│   on main.tf line 1, in resource "aiven_kafka" "aiven_kafka":
│    1: resource "aiven_kafka" "aiven_kafka" {
│
```

The resource looks like this:
```terraform
resource "aiven_kafka" "aiven_kafka" {
  project                 = local.project
  cloud_name              = local.aiven_default_cloud
  plan                    = var.cluster_plan
  disk_space              = var.disk_space
  service_name            = var.cluster_name
  project_vpc_id          = data.aiven_project_vpc.vpc.id
  maintenance_window_dow  = var.maintenance_window_dow
  maintenance_window_time = var.maintenance_window_time
  default_acl             = false
  termination_protection  = var.cluster_termination_protection_enabled
  karapace                = var.kafka_rest_enabled == true || var.schema_registry_enabled == true ? true : false
  static_ips              = var.static_ips_enabled ? aiven_static_ip.static_ips.*.static_ip_address_id : null
  kafka_user_config {
    static_ips = var.static_ips_enabled ? true : null

    ip_filter = concat(
      local.idealo_datacenter_ips,
      local.preisde_datacenter_ips,
      local.idealo_office_ip,
      local.aws_internal_cidr_blocks,
      local.sre_prometheus_nat_ip,
      var.custom_whitelist_ips
    )

    schema_registry = var.schema_registry_enabled ? "true" : "false"
    kafka_rest      = var.kafka_rest_enabled ? "true" : "false"

    kafka_authentication_methods {
      certificate = true
      sasl        = true
    }

    kafka {
      auto_create_topics_enable                                  = lookup(var.kafka_broker_settings, "auto_create_topics_enable", null)
      compression_type                                           = lookup(var.kafka_broker_settings, "compression_type", null)
      connections_max_idle_ms                                    = lookup(var.kafka_broker_settings, "connections_max_idle_ms", null)
      default_replication_factor                                 = lookup(var.kafka_broker_settings, "default_replication_factor", null)
      group_initial_rebalance_delay_ms                           = lookup(var.kafka_broker_settings, "group_initial_rebalance_delay_ms", null)
      group_max_session_timeout_ms                               = lookup(var.kafka_broker_settings, "group_max_session_timeout_ms", null)
      group_min_session_timeout_ms                               = lookup(var.kafka_broker_settings, "group_min_session_timeout_ms", null)
      log_cleaner_delete_retention_ms                            = lookup(var.kafka_broker_settings, "log_cleaner_delete_retention_ms", null)
      log_cleaner_max_compaction_lag_ms                          = lookup(var.kafka_broker_settings, "log_cleaner_max_compaction_lag_ms", null)
      log_cleaner_min_cleanable_ratio                            = lookup(var.kafka_broker_settings, "log_cleaner_min_cleanable_ratio", null)
      log_cleaner_min_compaction_lag_ms                          = lookup(var.kafka_broker_settings, "log_cleaner_min_compaction_lag_ms", null)
      log_cleanup_policy                                         = lookup(var.kafka_broker_settings, "log_cleanup_policy", null)
      log_flush_interval_messages                                = lookup(var.kafka_broker_settings, "log_flush_interval_messages", null)
      log_flush_interval_ms                                      = lookup(var.kafka_broker_settings, "log_flush_interval_ms", null)
      log_index_interval_bytes                                   = lookup(var.kafka_broker_settings, "log_index_interval_bytes", null)
      log_index_size_max_bytes                                   = lookup(var.kafka_broker_settings, "log_index_size_max_bytes", null)
      log_message_downconversion_enable                          = lookup(var.kafka_broker_settings, "log_message_downconversion_enable", null)
      log_message_timestamp_difference_max_ms                    = lookup(var.kafka_broker_settings, "log_message_timestamp_difference_max_ms", null)
      log_message_timestamp_type                                 = lookup(var.kafka_broker_settings, "log_message_timestamp_type", null)
      log_preallocate                                            = lookup(var.kafka_broker_settings, "log_preallocate", null)
      log_retention_bytes                                        = lookup(var.kafka_broker_settings, "log_retention_bytes", null)
      log_retention_hours                                        = lookup(var.kafka_broker_settings, "log_retention_hours", null)
      log_retention_ms                                           = lookup(var.kafka_broker_settings, "log_retention_ms", null)
      log_roll_jitter_ms                                         = lookup(var.kafka_broker_settings, "log_roll_jitter_ms", null)
      log_roll_ms                                                = lookup(var.kafka_broker_settings, "log_roll_ms", null)
      log_segment_bytes                                          = lookup(var.kafka_broker_settings, "log_segment_bytes", null)
      log_segment_delete_delay_ms                                = lookup(var.kafka_broker_settings, "log_segment_delete_delay_ms", null)
      max_connections_per_ip                                     = lookup(var.kafka_broker_settings, "max_connections_per_ip", null)
      max_incremental_fetch_session_cache_slots                  = lookup(var.kafka_broker_settings, "max_incremental_fetch_session_cache_slots", null)
      message_max_bytes                                          = lookup(var.kafka_broker_settings, "message_max_bytes", null)
      min_insync_replicas                                        = lookup(var.kafka_broker_settings, "min_insync_replicas", null)
      num_partitions                                             = lookup(var.kafka_broker_settings, "num_partitions", null)
      offsets_retention_minutes                                  = lookup(var.kafka_broker_settings, "offsets_retention_minutes", null)
      producer_purgatory_purge_interval_requests                 = lookup(var.kafka_broker_settings, "producer_purgatory_purge_interval_requests", null)
      replica_fetch_max_bytes                                    = lookup(var.kafka_broker_settings, "replica_fetch_max_bytes", null)
      replica_fetch_response_max_bytes                           = lookup(var.kafka_broker_settings, "replica_fetch_response_max_bytes", null)
      socket_request_max_bytes                                   = lookup(var.kafka_broker_settings, "socket_request_max_bytes", null)
      transaction_remove_expired_transaction_cleanup_interval_ms = lookup(var.kafka_broker_settings, "transaction_remove_expired_transaction_cleanup_interval_ms", null)
      transaction_state_log_segment_bytes                        = lookup(var.kafka_broker_settings, "transaction_state_log_segment_bytes", null)
    }

    public_access {
      kafka           = var.kafka_cluster_public_access_enabled
      prometheus      = var.prometheus_public_access_enabled
      kafka_rest      = var.kafka_rest_public_access_enabled
      schema_registry = var.schema_registry_public_access_enabled
    }
  }
}

```

This **doesn't** happen with **`v3.8.1`**

Note:

Removing the kafka block entirely then running `terraform apply` works on **`v3.11.0`** 

Any hints what might be wrong?

### PR DESCRIPTION
**Pull request by byashimov**
## About this change—what it does

Fixes service's user config "to api" serialisation. If object has null fields only it's not send nor casted to object.

Resolves #1033

### CODE REVIEW

**Comment by byashimov** [comment]
acc https://github.com/aiven/terraform-provider-aiven/actions/runs/3894704880

File: internal/schemautil/userconfig/apiconvert/toapi.go [hunk 1]
```diff
@@ -127,6 +127,12 @@ func objectItemToAPI(
 
 	fv := v[0]
 
+	// Object with only "null" fields becomes nil
+	// Which can't be cast into a map
+	if fv == nil {
```
Comment (Serpentiel) [inline internal/schemautil/userconfig/apiconvert/toapi.go:132]: we would wanna discuss it internally a bit, since it was made this way on purpose in the current version

**Review by Serpentiel — CHANGES_REQUESTED** [review]

**Review by Serpentiel — DISMISSED** [review]
lgtm

**Review by Serpentiel — APPROVED** [review]
lgtm
