### PR TITLE
fix(apiconvert): double apply necessity on migration

### LINKED ISSUE #1073: 4.0.0 pg_user_config.ip_filter_object does not set ips on aiven_pg
## What happened?
Following a deprecated warning on `ip_filter` after migrating from aiven provider 3.5.0 to 4.0.0, 
i change my code from
```
locals {
  aiven_static_ips = toset([
    "a.a.a.a/24",
    "b.b.b.b/24", 
  ])

resource "aiven_pg" "default" {
  ....
  pg_user_config {
    ip_filter = local.aiven_static_ips
  }
}
```
to 
```
resource "aiven_pg" "default" {
  ....
  pg_user_config {
    ip_filter_object {
      network     = "a.a.a.a/24"
      description = "some comment"
    }
    ip_filter_object {
      network     = "b.b.b.b/24"
      description = "some comment"
    }
  }
}
```

As effect, it remove all filters in aiven pg web interface, although there is no error or indication in `terraform apply`
Seems this append with a lot of filter applied

### PR DESCRIPTION
**Pull request by Serpentiel**
## About this change—what it does

fixes double apply necessity on migration from typeless keys to typed keys

resolves #1073 

## Why this way

to eliminate the bug

### CODE REVIEW

File: internal/schemautil/userconfig/apiconvert/toapi.go [hunk 1]
```diff
@@ -270,6 +270,57 @@ func itemToAPI(
 	return res, o, nil
 }
 
+// processManyToOneKeys is a function that processes many to one keys.
+func processManyToOneKeys(res map[string]interface{}, depthIdx int) {
```
Comment (ivan-savciuc) [inline internal/schemautil/userconfig/apiconvert/toapi.go:274]: Why do we need the `depthIdx` ? I see that we are using it conclusively like this `processManyToOneKeys(va, depthIdx+1)`, but I do not see it used anywhere else.

File: internal/schemautil/userconfig/apiconvert/toapi.go [hunk 2]
```diff
@@ -270,6 +270,57 @@ func itemToAPI(
...
+		}
+
+		if _, ok := mto[rk]; !ok {
+			mto[rk] = []string{}
+		}
+
+		mto[rk] = append(mto[rk], k)
+	}
+
+	for k, v := range mto {
```
Comment (ivan-savciuc) [inline internal/schemautil/userconfig/apiconvert/toapi.go:305]: It seems to me that we can simplify this function by removing this additional for and handling new values in the array from above. WDYT?

File: internal/schemautil/userconfig/apiconvert/toapi.go [hunk 3]
```diff
@@ -270,6 +270,57 @@ func itemToAPI(
 	return res, o, nil
 }
 
+// processManyToOneKeys is a function that processes many to one keys.
```
Comment (ivan-savciuc) [inline internal/schemautil/userconfig/apiconvert/toapi.go:273]: Please add another sentence to the comments describing how we are processing this. If I gather it correctly, we set only one value for a key for ip_filters and namespaces regardless of where it was _string or _object.

**Review by ivan-savciuc — COMMENTED** [review]
Some minor suggestions

File: internal/schemautil/userconfig/apiconvert/toapi.go (hunk 1 above)
Comment (Serpentiel) [reply internal/schemautil/userconfig/apiconvert/toapi.go:274]: ah, thanks for noticing this, looks like I used it in previous implementation

File: internal/schemautil/userconfig/apiconvert/toapi.go (hunk 2 above)
Comment (Serpentiel) [reply internal/schemautil/userconfig/apiconvert/toapi.go:318]: I checked further, looks like this can't be simplified any further, but thanks for the heads up!

File: internal/schemautil/userconfig/apiconvert/toapi.go (hunk 3 above)
Comment (Serpentiel) [reply internal/schemautil/userconfig/apiconvert/toapi.go:273]: added more comments

**Review by ivan-savciuc — APPROVED** [review]
LGTM
